/* SignIn */
export const REQ_SIGNIN = "REQ_SIGNIN";
export const RES_SIGNIN_SUCCESS = "RES_SIGNIN_SUCCESS";
export const RES_SIGNIN_FAILURE = "RES_SIGNIN_FAILURE";

/* Sign up */
export const REQ_SIGNUP = "REQ_SIGNUP";
export const RES_SIGNUP_SUCCESS = "RES_SIGNUP_SUCCESS";
export const RES_SIGNUP_FAILURE = "RES_SIGNUP_FAILURE";

/* Session check */
export const REQ_STATUS = "REQ_STATUS";
export const RES_STATUS_SUCCESS = "RES_STATUS_SUCCESS";
export const RES_STATUS_FAILURE = "RES_STATUS_FAILURE";

/* Sign out*/
export const REQ_SIGNOUT = "REQ_SIGNOUT";

/* Comment */
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const GET_COMMENTLIST = "GET_COMMENTLIST";
export const GET_COMMENTLIST_SUCCESS = "GET_COMMENTLIST_SUCCESS";
export const GET_COMMENTLIST_FAILURE = "GET_COMMENTLIST_FAILURE";

export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE";

export const DEL_COMMENT = "DEL_COMMENT";
export const DEL_COMMENT_SUCCESS = "DEL_COMMENT_SUCCESS";
export const DEL_COMMENT_FAILURE = "DEL_COMMENT_FAILURE";

/*Star*/
export const REQ_STAR = "REQ_STAR";
export const REQ_STAR_SUCCESS = "REQ_STAR_SUCCESS";
export const REQ_STAR_FAILURE = "REQ_STAR_FAILURE";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
